Nodename
isovalent/terraform-aws-talos pull request #171
Opened 2024-12-24 20:49 UTC by erikvveen

2024-12-24 20:50 UTC, erikvveen reviewed
nodename moet format volgen voor AWS CCM

2025-01-06 12:15 UTC, PhilipSchmid requested changes
Thanks for adding this!

A few things I'd like to address before merging this:
1. Please run `terraform fmt`
2. Please update the READMD.md TF doc by running `make docs`
3. Squash the two commits into a single one and add a proper commit message.

Thanks!

2025-01-06 12:15 UTC, PhilipSchmid commented on 00-variables.tf
> +
```suggestion
```

2025-01-10 16:33 UTC, erikvveen commented
Obsolete by https://github.com/isovalent/terraform-aws-talos/pull/173

2025-01-10 16:33 UTC, closed without merging